name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' # every 1 minute
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: llvm
          base: master
          head: master
